import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import 'bootstrap/dist/css/bootstrap.min.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a> Learning Blog </a>
        </h1>
       
        

        {/* <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p> */}

        <div className={styles.grid}>
          <div  className={styles.card}>
            <Link href="/about">
            <a className={styles.a}>About</a>
            </Link>
            <p>Find in-depth information about Learning Blog features .</p>
          </div>

          <div  className={styles.card}>
            <Link href="/blog">
            <a className={styles.a}>Blog</a>
            </Link>
            <p>Find  information about courses offered by  Learning Blog .</p>
          </div>

         
          

         <div  className={styles.card}>
            <Link href="/contact">
            <a className={styles.a}>Contact</a>
            </Link>
            <p>Contact us for more information.</p>
          </div>
        </div>
      </main>

    
    </div>
  )
}
